### PR TITLE
date now persists for user session with session state. bar graph added alongside pie chart.

### PR DESCRIPTION
**Pull request by VPeron**
added session_state variable to persist session data, expenses are appended to session_state lists. Added bar graph to display expenses but left pie chart on the app too.

if you want date to persist across sessions we would need to work together to add a google sheet on the background or stage a small db somewhere else.

### CODE REVIEW

**Comment by VPeron** [comment]
Hey @Free-Software-Sara ,
please let me know if this is not quite what you had in mind so we can work through it.

**Comment by Free-Software-Sara** [comment]
Hello @VPeron,
Apologies for reaching out this late. I was busy with my personal activities.
This code looks perfect.
I shall merge the same and host it in the cloud as well.
PS: Kudos on the clean coding

https://expense-tracker-day-to-day.streamlit.app/
The changes are reflected here

**Review by Free-Software-Sara — COMMENTED** [review]
Perfect !

**Comment by VPeron** [comment]
Glad to hear you liked it @Free-Software-Sara 

if you have more ideas that you would like to discuss/work on and think I'm a good fit to help, just give me a shout!

Otherwise, happy hacktoberfesting!

**Pull request merged**
